# Global Snakemake config for snakemake workflows run under Project a56
# Config specified here is merged with workflow-specific config

# File specifying PBS settings for Project a56
jobname: "{name}.{jobid}"
cluster: "pbs_submit.py"
cluster-status: "pbs_status.sh"
cluster-cancel: "qdel"

# Conda settings
conda-prefix: /g/data/a56/conda/snakecache/

# Singularity settings
use-singularity: true
singularity-prefix: "/g/data/a56/software/singularity/images"
singularity-args:   "--bind /g/data/a56,/scratch/a56"

# Snakemake settings
jobs: 1000
max-jobs-per-second: 1
max-status-checks-per-second: 10
latency-wait: 60
cores: 99
local-cores: 1 

# Default resources
default-resources:
  project: "a56"
  storage: "gdata/a56"
  runtime: "600" # minutes
  mem_mb: "4000"
  threads: "1"
  disk_mb: "100"
  jobmode: "profiles/global/resources/pbspro.template"
