#!/usr/bin/env python3

# This script submites a job script (generated by Snakemake) to PBS Pro when called by Snakemake
# Returns: the job id for the submitted job

import os, sys
import logging, traceback
from subprocess import Popen, PIPE
import yaml
import json
from snakemake.utils import read_job_properties

# Log config

logging.basicConfig(
    level=logging.INFO,
    format="CLUSTER: %(asctime)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

# Function definitions

def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return
    logging.error(
        "".join(
            ["Uncaught exception: ",*traceback.format_exception(exc_type, exc_value, exc_traceback),]
        )
    )

def get_job_name(job_properties):
    if job_properties["type"] == "single":
        return job_properties["rule"]
    elif job_properties["type"] == "group":
        return job_properties["groupid"]
    else:
        raise NotImplementedError(
            f"Don't know what to do with job_properties['type']=={job_properties['type']}"
        )


## Beginning of the script
    
# Install exception handler
sys.excepthook = handle_exception

wrapper_directory = os.path.dirname(__file__)

jobscript = sys.argv[1]
job_properties = read_job_properties(jobscript)
logging.debug("Job properties: " + json.dumps(job_properties))

# resources defined in rules, profile or from command line
params = job_properties["resources"]

params["name"]  = get_job_name(job_properties)
params["jobid"] = job_properties["jobid"]

# Only include mem_mb and disk_mb -- ignore other (equivalent) mem/disk specifications
for res in ['mem', 'mem_mib', 'mem_gb', 'disk', 'disk_mib', 'disk_gb']:
    try:
        del params[res]
    except KeyError:
        pass

logging.debug("Final params: " + json.dumps(params))

# check which system you are on and load command command_options
key_mapping_file = os.path.join(wrapper_directory, "key_mapping.yaml")
command_options = yaml.load(open(key_mapping_file), Loader=yaml.BaseLoader)
system = command_options["system"]
command = command_options[system]["command"]
key_mapping = command_options[system]["key_mapping"]

# construct command:
for key in params:
    if (key not in key_mapping) and (key != 'tmpdir'):
        logging.warning(
            f"parameter '{key}' not in keymapping! It would be better if you add the key to the file: {key_mapping_file} \n I try without the key!"
        )
    elif (key == "operand") or (key == 'tmpdir') or (key == "jobid"):
        pass
    else:
        command += " "
        command += key_mapping[key].format(params[key])

command += " -o logs/joblogs/{}.{}.log -- ".format(params["name"], params["jobid"])
command += " {}".format(jobscript)
logging.info("submit command: " + command)

p = Popen(command.split(), stdout=PIPE, stderr=PIPE)
output, error = p.communicate()
if p.returncode != 0:
    error_message = "Job can't be submitted\n" + output.decode("utf-8") + error.decode("utf-8")
    logging.error(error_message)
    #give it to snakemake
    print(error_message)
    exit(p.returncode)
else:
    res = output.decode("utf-8")
    if system == "lsf":
        import re
        match = re.search(r"Job <(\d+)> is submitted", res)
        jobid = match.group(1)
    elif system == "pbs" or system == "pbspro":
        jobid = res.strip().split(".")[0]
    else:
        jobid = res.strip().split()[-1]
    print(jobid)
