#!/usr/bin/env python3

# This script submites a job script (generated by Snakemake) to PBS Pro when called by Snakemake
# Returns: the job id for the submitted job

import os, sys
import logging, traceback
from subprocess import Popen, PIPE
import yaml
import json
from snakemake.utils import read_job_properties

# Log config

logging.basicConfig(
    level=logging.INFO,
    format="CLUSTER: %(asctime)s %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

# Function definitions

def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return
    logging.error(
        "".join(
            ["Uncaught exception: ",*traceback.format_exception(exc_type, exc_value, exc_traceback),]
        )
    )

def get_job_name(job_properties):
    if job_properties["type"] == "single":
        return job_properties["rule"]
    elif job_properties["type"] == "group":
        return job_properties["groupid"]
    else:
        raise NotImplementedError(
            f"Don't know what to do with job_properties['type']=={job_properties['type']}"
        )

# This function selects an appropriate queue depending on the mem and jobfs requirements
# The selection is based on the NCI queue limits: https://opus.nci.org.au/display/Help/Queue+Limits
# Note that queues have minimum (as as well as maximum) mem requirements, but not jobfs
# TODO: consider network and GPU usage
def select_queue(mem,jobfs):
    # Constants (in MB)
    NORMAL_MAX_MEM=196608
    HUGEMEM_MAX_MEM=1402901780
    NORMAL_MAX_JOBFS=409600
    HUGEMEM_MAX_JOBFS=1433600
    # First look at jobfs
    # Increase mem if necessary
    if jobfs < NORMAL_MAX_JOBFS:
        queue = 'normal'
    elif jobfs < HUGEMEM_MAX_JOBFS:
        queue = 'hugemem'
        mem = max(mem,NORMAL_MAX_MEM+1024)
    else:
        queue = 'memgamem'
        mem = max(mem,HUGEMEM_MAX_MEM+1024)
    # Now look at mem
    if mem < NORMAL_MAX_MEM:
        queue = 'normal'
    elif mem < HUGEMEM_MAX_MEM:
        queue = 'hugemem'
    else:
        queue = 'memgamem'
    # Return queue string, plus updated mem string
    # Note that if '-l mem={mem}' is specified twice with qsub
    # then only the second value is used
    return f" -l mem={mem}mb -q {queue}"

def calculate_walltime(runtime):
    # "runtime" is a standard Snakemake resource, measured in minutes: 
    # https://snakemake.readthedocs.io/en/v7.32.3/snakefiles/rules.html#standard-resources
    # "walltime" is a qsub option for PBS Pro, measured in seconds
    walltime=runtime*60
    return f" -l walltime={walltime} "

## Beginning of the script
    
# Install exception handler
sys.excepthook = handle_exception

wrapper_directory = os.path.dirname(__file__)

jobscript = sys.argv[1]
job_properties = read_job_properties(jobscript)
logging.debug("Job properties: " + json.dumps(job_properties))

# resources defined in rules, profile or from command line
params = job_properties["resources"]

params["name"]  = get_job_name(job_properties)
params["jobid"] = job_properties["jobid"]

# Only include mem_mb and disk_mb -- ignore other (equivalent) mem/disk specifications
for res in ['mem', 'mem_mib', 'mem_gb', 'disk', 'disk_mib', 'disk_gb']:
    try:
        del params[res]
    except KeyError:
        pass

logging.debug("Final params: " + json.dumps(params))

# check which system you are on and load command command_options
key_mapping_file = os.path.join(wrapper_directory, "key_mapping.yaml")
command_options = yaml.load(open(key_mapping_file), Loader=yaml.BaseLoader)
system = command_options["system"]
command = command_options[system]["command"]
key_mapping = command_options[system]["key_mapping"]

# construct command:
for key in params:
    if (key not in key_mapping) and (key != 'tmpdir'):
        logging.warning(
            f"parameter '{key}' not in keymapping! It would be better if you add the key to the file: {key_mapping_file} \n I try without the key!"
        )
    elif (key == "operand") or (key == 'tmpdir') or (key == "jobid") or (key == "runtime"):
        pass
    else:
        command += " "
        command += key_mapping[key].format(params[key])


command += select_queue(params["mem_mb"], params["disk_mb"])
command += calculate_walltime(params["runtime"])
command += " -o logs/joblogs/{}.{}.log -- ".format(params["name"], params["jobid"])
command += " {}".format(jobscript)
logging.info("submit command: " + command)

p = Popen(command.split(), stdout=PIPE, stderr=PIPE)
output, error = p.communicate()
if p.returncode != 0:
    error_message = "Job can't be submitted\n" + output.decode("utf-8") + error.decode("utf-8")
    logging.error(error_message)
    #give it to snakemake
    print(error_message)
    exit(p.returncode)
else:
    res = output.decode("utf-8")
    if system == "lsf":
        import re
        match = re.search(r"Job <(\d+)> is submitted", res)
        jobid = match.group(1)
    elif system == "pbs" or system == "pbspro":
        jobid = res.strip().split(".")[0]
    else:
        jobid = res.strip().split()[-1]
    print(jobid)
